# note: cocurrency is used at workflow level or at the job level
# It is used for mainly to "to run only one job at a time".

name: concurrency job

on: 
  workflow_dispatch: 

env: 
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: hello-world
 

jobs:  
  docker-build: 
    runs-on: ubuntu-latest
    steps:
     - name: docker build
       run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

     - name: docker login
       run: echo docker login --username ${{ vars.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

     - name: docker push/publish
       run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy: 
    needs: docker-build
    concurrency: 
        group: production-deploy
        cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
     - name: deploy
       run: |
         echo docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
         sleep 300
           