name: My First Workflow

on: push  # This workflow will run on every push
          
jobs:     # A workflow run is made up of one or more jobs that can run sequentially or in parallel
   first-job:  # This job is named first-job 
        runs-on: ubuntu-latest  # This job runs on the latest version of Ubuntu
        steps:  # A job consists of an ordered list of steps
        - name: checkout Repo
          uses: actions/checkout@v4

        - name: Welcome message
          run: echo "Welcome to GitHub Actions"

        - name: List files
          run: ls -a
          
        - name: Read the file
          run: cat README.md  
            
 # notes: Run cat README.md
#cat: README.md: No such file or directory
#Error: Process completed with exit code 1. 
   # And it does not have access to the files in the repository. 
    # This is because the job runs in a fresh virtual environment.
    # To access the files in the repository, we need to checkout the repository.
    # We can do this by adding the following step to the job. 
    # we can find actions in the GitHub Actions Marketplace website. 

         