
name: Execute Shell Script

on: 
  - push
  
jobs:
    execute-shell-script: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
       
        - name: List files
          run: ls -ltra
          
        - name: Give permission to script, Execute script
          run: |
            sudo apt install cowsay -y
            cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
            grep -i "dragon" dragon.txt
            cat dragon.txt
            ls -ltra
            
       
         
    
    