
name: Execute Shell Script

on: 
  - push
  
jobs:
    execute-shell-script: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
       
        - name: List files
          run: ls -ltra
          
        - name: Give permission to script, Execute script
          run: ./ascii-script.sh
            
            
            
       
         
    
    
