name: Generate ASCII Artwork

on: 
  - push
  
jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          
        - name: List and Read files
          run: |
            echo "Welcome to Github Actions Workflow"
            ls -a
            cat README.md

        - name: Generate ASCII Artwork
          run: sudo apt install cowsay -y
          
        - name: Execute cowsay cmd
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
          
        - name: Test the file exits
          run: grep -i "dragon" dragon.txt
          
        - name: Read file
          run: cat dragon.txt
          
        - name: List repo files
          run: ls -a  
    
    