# here we have 2 jobs, build and deploy, we want to deploy the job. Only when the branch is main.
# creating new branch named feature/testing. 


name: if condition-in-context

on: push

env: 
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: hello-world
 

jobs:  
  docker-build: 
    runs-on: ubuntu-latest
    steps:
     - name: docker build
       run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

     - name: docker login
       run: echo docker login --username ${{ vars.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

     - name: docker push/publish
       run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

  deploy: 
    if: github.ref == 'refs/heads/main' 
    needs: docker-build
    runs-on: ubuntu-latest
    steps:
     - name: deploy
       run: echo docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
         