name: my-first-workflow

on: 
  - push

jobs: 
    workflow-job: 
        runs-on: ubuntu-latest
        steps: 
        - name: Checkout Repository
          uses: actions/checkout@v4
          
        - name: List and Read files
          run: |
            echo "Welcome to Github Actions Workflow"
            ls -a
            cat README.md