# needs syntax should be given at Job level.
# How to Upload the Artifact, And Download the Artifact.
# In this commit we Added Upload and Download Artifact Syntax, pls take a look once.
name: Build Test Deploy

on: 
  - push
  
jobs:
    build_job_1: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
       
        - name: Install cowsay program
          run: sudo apt install cowsay -y

        - name: Execute cowsay command
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

        - name: Upload the Artifact  
          uses: actions/upload-artifact@v4
          with:
            name: dragon-text.txt
            path: dragon.txt
          
        - name: List files
          run: ls -ltra
          
    test_job_2: 
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
          - name: Download the Artifact  
            uses: actions/download-artifact@v4
            with:
              name: dragon-text.txt

          - name: Test file Exits
            run: grep -i "dragon" dragon.txt

    deploy_job_1: 
        needs: test_job_2
        runs-on: ubuntu-latest
        steps: 
          - name: Download the Artifact  
            uses: actions/download-artifact@v4
            with:
              name: dragon-text.txt

          - name: Read file
            run: cat dragon.txt
            
          - name: Deploy
            run: echo "Deploying........"  