# workflow filters events and activity types

name: workflow filters events and activity types

on: 
    push:
      branches: 
        - main           # it triggers the workkflow, if there is apush to the main branch.
        - '!feature/*'   # ignoreing push to any branch name starting with feature using !
   # schedule:        
   # workflow_dispatch: 

    pull_request: 
        types: 
          - opened
          - closed

        paths-ignore:    # Workflow will only run a pull request taht includes a change on any file other than README.md.  
          - README.md 
          
        branches: 
          - main     # configure your workflow to only run on pull request that target specific branch.    


          


env: 
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: hello-world
 

jobs:  
  docker-build: 
    runs-on: ubuntu-latest
    steps: 
      - run: echo this workflow/job/step is executed for event type - ${{ github.event_name }} 
             

